# Generated by Django 3.1.2 on 2021-02-08 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('points', models.FloatField(null=True)),
                ('player_level', models.CharField(choices=[('Amateur', 'Amateur'), ('Intermediate', 'Intermediate'), ('Professional', 'Professional'), ('World Class', 'World Class'), ('Champion', 'Champion')], max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile_pic_default.png', null=True, upload_to='')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
