# Generated by Django 3.1.2 on 2021-02-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_level',
            field=models.CharField(choices=[('Amateur', 'Amateur'), ('Intermediate', 'Intermediate'), ('Professional', 'Professional'), ('World Class', 'World Class'), ('Champion', 'Champion')], default='Amateur', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='points',
            field=models.FloatField(default=0, null=True),
        ),
    ]
